name: Build and Test PHP Extension

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ['8.0', '8.1']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl

      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y autoconf automake libtool bison re2c

      - name: Prepare build
        run: |
          phpize
          ./configure
          make

      - name: Run tests
        run: make test

      - name: Run demo
        run: |
          php -d extension=./modules/rayaop.so -i | grep rayaop
          php -d extension=./modules/rayaop.so rayaop.php